title: ""
description: ""
theme: jekyll-theme-cayman
show_downloads: false
github:
  is_project_page: false

# (Keep your existing fields)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
